# Generated by Django 6.0.1 on 2026-01-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_created_at_alter_userprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('fat_loss', 'Fat Loss'), ('lean_muscle', 'Lean Muscle'), ('fitness', 'General Fitness')], max_length=100),
        ),
    ]
